version: '3.8'
services:
  node-rest-api:
    container_name: node-rest-api
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: sh -c 'npm install && npm run start:dev'
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/app/
      - /app/node_modules